### ISSUE TITLE
Demos are not working

### ISSUE THREAD

**Issue by jincypjose** [unfoldingWord/translation-helps-rcl#124]
Demos are not working for most of the components.So it is harder to debug

**Comment by Joel-C-Johnson** [comment]
- [CardContent](https://translation-helps-rcl.netlify.app/#cardcontent)
- [TqContent](https://translation-helps-rcl.netlify.app/#tqcontent)
- [TsvContent](https://translation-helps-rcl.netlify.app/#tsvcontent)
- [TsvList](https://translation-helps-rcl.netlify.app/#tsvlist)
- [TwNavigationDemo](https://translation-helps-rcl.netlify.app/#twnavigationdemo)

**Comment by jincypjose** [comment]
Also to resolve this issue we figured out in which ever component the useContent hook is being used if we are passing 
`readyToFetch = true`, we will get a data from api and wil be able to demo a component

**Comment by Joel-C-Johnson** [comment]
@jincypjose can you review this PR - https://github.com/unfoldingWord/translation-helps-rcl/pull/125

**Comment by elsylambert** [comment]
@Joel-C-Johnson Is there a way QA can test the Demos?
